- build.gradle
- src/main/java/com/devcourse/checkmoi/global/config/QueryDslConfig.java
> 🔧 chore : QueryDsl 설정 추가

- src/test/java/com/devcourse/checkmoi/config/QueryConfig.java
- src/test/java/com/devcourse/checkmoi/template/ApiTest.java
- src/test/java/com/devcourse/checkmoi/template/RepositoryTest.java
- src/test/java/com/devcourse/checkmoi/util/DocumentUtil.java
각 테스트에서 공통적으로 쓰이는 부분을 따로 빼서 설정
resolves #21
> 🧪 test : 테스트 기본 템플릿 설정

- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
- src/main/java/com/devcourse/checkmoi/global/security/handler/JwtAuthenticationEntryPoint.java
다음과 같이 변경 후 해결이 되었지만, 이유를 좀 더 알아봐야 할 듯 합니다.. 😢 
resolves #31
> 🐛 fix : 페이지 조회 권한 수정

- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
여러번 로그인 했을 때 Exception 나는 부분 해결
resolves #35
> 🐛 fix : 다중 로그인 이슈

- .github/PULL_REQUEST_TEMPLATE.md
resolves를 리스트 형식으로 변경
- resolves #46
> 📝 docs : PR 템플릿 변경

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyMemberStub.java
- src/test/java/com/devcourse/checkmoi/domain/user/stub/UserStub.java
- 스터디를 생성한 유저가 스터디장이 되도록 StudyMember에 OWNED로 추가
- 그에따른 테스트 코드 변경
solves #28
> 🐛 fix : 스터디를 생성한 유저가 스터디장이 되도록 구현

- src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
- src/main/java/com/devcourse/checkmoi/domain/user/converter/UserConverter.java
- src/main/java/com/devcourse/checkmoi/domain/user/dto/UserResponse.java
- src/main/java/com/devcourse/checkmoi/domain/user/dto/UserStudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/user/model/UserRole.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepository.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/UserRepository.java
- src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/security/oauth/UserProfile.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/user/stub/UserStub.java
현재는 user쪽에서 스터디를 쿼리 하고 있는데, 스터디 서비스를 통해 스터디 info를 받아오도록 변경해야 합니다
스터디 이슈 하나 처리하고 해당 부분을 새로운 이슈로 등록해서 리팩토링 추가 진행하겠습니다!!!
- resolves #48
> ♻️ refactor : 유저 스터디 조회

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
dev, prod 프로파일 RDS 사용을 위한 datasource 설정
- resolves #58
> 🔧 chore : 서버 RDS datasource 설정

- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
- ddl-auto update를 사용하도록 변경
- resolves #58
> 🔧 chore : ddl-auto update 전략 사용

- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
Api 테스트 코드 문서화 부분의 summary에 개발중 표시
- resolves #63
> 📝 docs : 현재 사용불가능한 API에 대해서 개발중 표시

- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- 스터디 정보 수정에 대해서 상태변경도 하도록 변경했습니다.
- 이에 맞춰 테스트코드와 API 문서를 수정했습니다.
- resolves #30
> ♻️ refactor : 스터디 정보 수정에 상태 변경도 가능하도록 변경

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
스터디 생성시 생성한 유저의 상태를 PENDING이 아닌 OWNED로 변경
- resolves #71
> 🐛 fix : 스터디 수정에서 스터디 장을 불러올때 null이 넘어오는 현상 해결

- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
```
.antMatchers(HttpMethod.OPTIONS, "*").permitAll()
```
> 🐛 fix : OPTIONS permission 변경

- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
* 스웨거 문서에 대해서 filter를 타지 않도록 수정
- resolves #80
> 🐛 fix : 스웨거 403 이슈 수정

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/user/api/AuthApi.java
- src/main/java/com/devcourse/checkmoi/global/aop/ControllerLoggingAspect.java
API를 호출하면 어떤곳에서 호출되었는지 출력한다
- `controller` : 컨트롤러 클래스 명
- `http_method` : 요청 HTTP메서드
- `method` : 동작한 method 명
- `params` : 파라미터
- `log_time` : 시간
- `request_uri` : 요청 URL
일단 현재 로깅 모두 info로 찍고 있습니다
- resolves #74
> ✨ feat : API 호출 로깅

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- src/main/resources/application-aws.yml
- src/main/resources/application.yml
dev, prod 파일에 S3 환경변수를 추가함
application-aws.yml 파일의 오타를 수정함
- resolves #83
> 🐛 fix : 환경변수 설정을 추가한다 (#83)

- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
- src/main/java/com/devcourse/checkmoi/domain/user/converter/UserConverter.java
- src/main/java/com/devcourse/checkmoi/domain/user/dto/UserResponse.java
- src/main/java/com/devcourse/checkmoi/domain/user/model/User.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/token/api/TokenApiTest.java
- src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
기능은 아직 없지만, 프론트 작업을 위해 온도 정보를 추가하였습니다
- resolves #82
> ✨ feat : 유저 온도 정보 추가

- src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
매번 로그인하기 귀찮기 때문에, 임시 access토큰을 발급받는 api를 작성하였습니당
- 7번이 더미 유저이기 때문에 /api/tokens/7로 발급받으시면 됩니다
- resolves #87
> ✨ feat : 토큰 편의 메서드 작성

- src/main/java/com/devcourse/checkmoi/domain/book/model/Book.java
기존 50자에서 150자로 수정
- resolves #98
> ♻️ refactor : 책제목 길이 수정

- src/main/java/com/devcourse/checkmoi/domain/book/repository/CustomBookRepositoryImpl.java
> ⏪️ Revert  : 🐛 fix   최근에 스터디를 생성한 책 순으로 정렬시 책이 중복되어 나오는 현상"

- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
- src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
- DB에 쿼리 조회시 중복 제거하는 구문 추가
- resolves #104
> 🐛 fix : 최근에 스터디를 생성한 책 순으로 정렬시 책이 중복되어 나오는 현상 

- src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
- src/main/resources/application-security.yml
> 🐛 fix : 토큰 교환 방식 변경

- src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
- src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryService.java
- src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
> ✨ feat : 다른회원 정보 조회 기능 추가

- src/main/java/com/devcourse/checkmoi/global/config/JacksonDeserializeConfig.java
- jsonMapperJava8DateTimeModule Bean에서 LocalDate에 대한 값을 직접받아 "/"를 "-"로 변환하도록 만들도록 수정
- resolves #118
> ✨ feat : Date를 받을 경우 추가적으로 역직렬화 처리를 해주도록 구현

- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
> 🔧 chore : 사용 포트 추가

- src/main/java/com/devcourse/checkmoi/domain/post/api/PostApi.java
- src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
- src/main/java/com/devcourse/checkmoi/domain/post/exception/PostNoPermissionException.java
- src/main/java/com/devcourse/checkmoi/domain/post/exception/PostNotFoundException.java
- src/main/java/com/devcourse/checkmoi/domain/post/model/Post.java
- src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/PostRepository.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/validator/PostServiceValidator.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/validator/PostServiceValidatorImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
- src/main/java/com/devcourse/checkmoi/global/exception/InvalidValueException.java
- src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/converter/PostConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/validator/PostServiceValidatorImplTest.java
- src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
PR이 커져버렸슴다... 죄송함다 ㅠ
작업 내용은 게시글에 대한 전체적인 API를 러프하게 작성해 보았습니다
대략적인 스웨거 내용은 밑에 링크에 포함하였습니다.
[postAPi초안.pdf](https://github.com/prgrms-web-devcourse/Team-Books-CheckMoi-BE/files/9274821/postAPi.pdf)
- 게시글 검색의 경우 검색조건이 정해지지 않아 우선 id=null로 나오는 상태입니다.
- validation이 되어있지 않고 API 문서와 컨벤션에 맞는 레이아웃을 우선적으로 제작하였습니다.
- resolves #127
> ✨ feat : 게시글 API 초안

- src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
- src/main/java/com/devcourse/checkmoi/domain/comment/converter/CommentConverter.java
- src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentRequest.java
- src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentResponse.java
- src/main/java/com/devcourse/checkmoi/domain/comment/model/Comment.java
- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CommentRepository.java
- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomCommentRepository.java
- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomPostRepository.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/comment/converter/CommentConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
현재 검색조건은 postId 하나입니다!
- resolves #130
> ✨ feat : 댓글 조건별 검색 기능

- build.gradle
- src/main/java/com/devcourse/checkmoi/global/config/SecurityConfig.java
- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
- src/main/java/com/devcourse/checkmoi/global/config/properties/CorsConfigProperties.java
- src/main/java/com/devcourse/checkmoi/global/config/properties/SecurityConfigProperties.java
- src/main/resources/application-security.yml
- src/main/resources/application-test.yml
제가 깃을 꼬아버려서 복구하는 PR입니다 😿  원본 PR은 다음과 같습니다
- https://github.com/prgrms-web-devcourse/Team-Books-CheckMoi-BE/pull/143
> 🔧 chore : yml을 통해 시큐리티 설정 정보 관리

- src/main/resources/application-security.yml
> 🔧 chore : study 도메인 시큐리티 허용범위 수정

- build.gradle
- src/main/resources/application-dev.yml
- src/main/resources/application-prod.yml
[flyway 기능 적용](https://www.notion.so/backend-devcourse/Flyway-6f7d54bf276c492cbd2b8c2118cce7cf)
- 해당 기능을 사용하기 전 기초적인 개념을 익히고 사용하면 좋을 것 같습니다.
- version 관리 DDL의 naming convention을 정해야합니다.
> 🔧 chore : flyway 기능 적용

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/model/PageRequest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
검색 조건에 맞게 사용할 수 있는 통합 스터디 조회 API를 제작하였습니다.
검색 조건은 다음과 같습니다.
페이징은 아직 되어있지 않습니다.
v1과 함께 전체프로젝트에서 통용시킬 페이징을 고려해야 할 것 같습니다
- resolves #158
> ✨ feat : 스터디 조회 API v2

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/facade/StudyUserFacadeImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
- totalPage의 필요성때문에 study 리스트 조회시 페이지네이션을 적용하도록 수정
- resolves #43
> ♻️ refactor : study 리스트 조회에 대해서 페이징 적용

- src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
- src/main/java/com/devcourse/checkmoi/domain/book/dto/BookRequest.java
- src/main/java/com/devcourse/checkmoi/domain/book/service/BookCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
- src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentRequest.java
- src/main/java/com/devcourse/checkmoi/domain/post/api/PostApi.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
- src/main/java/com/devcourse/checkmoi/domain/user/dto/UserRequest.java
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
dto 기본 validation 메시지를 추가하였습니다.
서버에러입니다
- resolves #166
> ✨ feat : dto 에러메시지 추가

- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
스터디 멤버 상태가 ACCEPTED 상태이면서 스터디가 끝나지 않은 상태를 질의하는 검색 조건 추가
- resolves #175
> ✨ feat : 스터디 검색 조건 추가

- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMemberStatus.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnum.java
- src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnumValidator.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
- 전달된 값이 Enum인지 확인하는 @ValueOfEnum 어노테이션 구현
- 언더바(_)를 받지 않고 대소문자를 구분하지 않도록 하여 검증이 필요한 Enum에nameOf() 메서드 추가
- resolves #162
> ♻️ refactor : 전달된 값이 Enum인지 확인하는 커스텀 어노테이션 추가

- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
이전 PR에서 작성하지 못했던 테스트를 추가했습니다
참여하고 있는 스터디 조건에 스터디장의 조건도 추가하였습니다.
- resolves #175
> ♻️ refactor : 스터디 검색 조건 수정

- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
유저 정보 조회시 전체 조회 되는 부분과 PENDING상태 뜨는 부분 수정
나머지 운동 다녀와서 마저 작업하겟슴다..!!!
- resolves #195
> 🐛 fix : 유저 정보 조회시 데이터 개수 조절

- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
스터디 신청 목록 조회시 스터디가 실제 존재하는지 확인하는 로직을 추가했습니다
- #198
> ♻️ refactor : 스터디 신청 목록 API에  스터디 존재여부 확인 로직 추가

- src/main/java/com/devcourse/checkmoi/domain/study/exception/NotRecruitingStudyException.java
- src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyMemberFullException.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
- 다음 기능 validation 추가
- 스터디 상태는 모집중이어야 한다 ( Study 에서 확인 →IsRecruiting return boolean )
- maxParticipant 이상으로 승인할 수 없다
- validation에서 사용하는 커스텀 Exception 추가
- 이에 따른 테스트 코드 추가
- resolves #200
> ♻️ refactor : 스터디 승인/거절 기능 validation 추가

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyFacade.java
- src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyFacadeImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/facade/StudyFacadeImplTest.java
- src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
상위 계층에서 bookService에게 실제 책이 존재하는지 확인하고 스터디를 생성하도록 로직 수정
상위 계층에서 bookService에게 실제 책이 존재하는지 확인하고 스터디를 조회하도록 로직 수정
- resolves #204
> ♻️ refactor : 스터디 생성시 책이 존재하는지 확인하는 로직 추가

- src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
- src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
게시글 info -> 작성자 id 추가
- resolves #208
> ✨ feat : 게시글 정보 글쓴이 아이디 추가

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/main/resources/application-security.yml
- src/main/resources/application-test.yml
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
메인화면에서 책을 불러오는 부분에 시큐리티 권한이 열려있지 않아 수정하였습니다.
좌물쇠 제거
- resolves #156
> 🔧 chore : v2 GET 메소드 권한 수정

- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
스웨거를 매번 강력 새로고침해야 하는 문제점을 느껴
리소스를 캐싱하지 않도록 수정했습니다
- resolves #212 
- resolves #156
> 🔧 chore : 서버 Cache 전략 변경

- src/test/java/com/devcourse/checkmoi/domain/token/api/TokenApiTest.java
> 📝 docs : 토큰 스웨거 문서 추가

- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
- src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
다음 부분에 대해서 validation 추가
- 스터디 모집중에만 스터디를 신청할 수 있다
- maxParticipant 도달시 신청 못한다
- resolves #217
> ♻️ refactor : 스터디 신청 validation 추가

- src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
- src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtTokenProvider.java
> ✨ feat : 테스트용 토큰 발급

- src/main/resources/application-security.yml
- src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
스웨거 문서화
토큰 만료시간 수정
- resolves #226
- resolves #227
> 🔧 chore : 227 토큰관련설정변경

- src/main/java/com/devcourse/checkmoi/domain/token/api/TokenApi.java
- src/main/java/com/devcourse/checkmoi/domain/token/dto/TokenRequest.java
- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
- src/main/java/com/devcourse/checkmoi/global/exception/handler/GlobalExceptionHandler.java
- src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/devcourse/checkmoi/global/security/jwt/JwtTokenProvider.java
- src/main/java/com/devcourse/checkmoi/global/security/oauth/OAuthService.java
- src/main/resources/application-security.yml
> 🔧 chore : 227 토큰관련설정변경2

- src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
스터디 상태 변경 주기를 매 시간 30분에 업데이트 하기로 변경했습니다
- resolves #231
> ♻️ refactor : 스터디 상태 크론 시간 변경

- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
이전의 계산로직이 잘못되어 빠른 반영을 위해 PageImpl 을 사용하여 변경하였습니다
어플 내 다른 Pagination 부분의 구현과 통일화하였습니다
- resolves #233
> 🐛 fix : 페이지네이션을 통해 totalPage 가져오는 부분 변경 (#233)

- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
내 정보 조회시 스터디를 최근 가입한 순으로 정렬하도록 변경
- resolves #241
> ♻️ refactor : 내 정보 조회시 스터디를 최근 가입한 순으로 정렬

- README.md
- 프론트 레포 URL
- 회고 링크 추가
생각해보니 이거 배포하면 리드미 수정하기 귀찮아 질 것 같아서 미리 링크를 걸어두는게 좋아보인다고 판단했습니다
- resolves #247
> 📝 docs : 리드미 수정 2

- intellij-java-checkmoi-style.xml
- src/main/java/com/devcourse/checkmoi/global/log/AuthToMdcFilter.java
- src/main/java/com/devcourse/checkmoi/global/log/aop/ControllerLoggingAspect.java
- src/main/resources/application.yml
- src/main/resources/logback.xml
( 캡쳐에는 없지만 에러 로그 파일도 max 사이즈 설정하여, 최대 크기 도달시 0->1->2.. 이런식으로 파일 생성되도록 하였습니다.  )
[ LoginUserId-유저식별자 ] 로 출력합니다
maxFileSize 도달시 yyyymmdd.숫자.log 의 숫자가 증가하며 새로운 파일이 생성됩니다
캡쳐처럼 **LOG_PATH_IS_UNDEFINED 가 계속 생겨나는데 다른 분들도 테스트 해보시는게 좋을 것 같습**니다 
codestyle 변경해서 적용해주셔야합니다. 안그러면 property 태그가 하단으로 자동정렬되어서 인식이 안됩니다 
- 에러 로그가 저장되는 파일 
- INFO 레벨 이상의 로그가 저장되는 파일
두 가지가 저장됩니다. 
@zxcv9203 용철님 에러로그파일은 "달"기준으로 만들도록 하셨던 의도가 있으셨을까용?? + 지난번처럼 /var/logs 하위에 저장해보면 괜찮으려나요...🤔 
- resolves #249
> ✨ feat : 로그인 사용자를 로그에 출력하도록 logback 설정

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
- src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
- src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
pubDate -> pubdate로 반환하도록 수정
- resolves #254
> 🐛 fix : 프론트에서 출판일자가 출력되지 않는 현상 수정

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/book/converter/BookConverter.java
- src/main/java/com/devcourse/checkmoi/domain/book/dto/BookResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/api/ScheduleApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/book/converter/BookConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/book/stub/NewDummyData.java
- src/test/java/com/devcourse/checkmoi/domain/book/stub/PersistedDummyData.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/global/scheduler/SchedulerTest.java
- src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
pubDate -> pubdate로 반환하도록 수정
수동으로 스케줄링을 호출하는 함수 추가
> 🚀 release : CheckMoi v3.1.0 
