prgrms-web-devcourse/Team-Books-CheckMoi-BE

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
자동 배포중 상황에 맞는 서버 주소 지정을 위해 secrets에서 불러올때 "export SERVER_NAME=서버 주소" 와 같은 형태로 변경
resolved : #25
> 🐛 fix : 자동 배포중 Export로 서버 네임 지정하는 구문 에러 발생

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/converter/StudyConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- 책 + 스터디 정보를 요청을 보내면 스터디를 생성해주는 API 구현 및 해당 API 필요한 기능 구현
- API, Service, Converter에 대한 테스트 코드 구현
- openapi3에 Oauth2를 인증할 수 있도록 OAuth2 인증방식과 token 서버, 인증 서버 URL 추가
다음은 해당 API의 스웨거 화면입니다. (스웨거는 https://dev.checkmoi.ga/docs/index.html 에서 확인할 수 있습니다.)
- 현재 시큐리티 설정으로 인해 API 테스트시 401 에러가 계속해서 발생하여 실제 API 테스트는 성공하지 못했습니다. (유닛테스트는 전부 완료하였습니다.) 
- Jacoco 테스트 커버리지를 충족하기 위해 일단 작성했던 내용은 제거하고 먼저, 생성에 대한 기능만 포함하도록 작성 내용을 변경하였습니다. 이전의 내용은 feat/6 브랜치에서 계속해서 확인 가능합니다.
resolves #28
> ✨ feat : 스터디 생성 기능 구현

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyJoinRequestNotFoundException.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- 스터디 가입 승낙 및 거절 기능 구현
- 해당 기능이 단순한 상태변경만 제공하면 된다고 판단해 응답으로 204를 보내도록 처리했습니다.
- 스터디 존재 여부와 스터디 신청 여부 존재 확인 로직 구현 및 Exception 추가
- 상태변경에 대한 DTO 추가
- 테스트 코드 추가 및 API 문서화 추가
- 스터디 검증 로직 추가로 인한 스터디 정보 수정 기능에 해당 로직 적용
해당 API에 대한 정보입니다.
resolves #37
> ✨ feat : 스터디 가입 승낙 및 거절

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyMemberRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/model/PageRequest.java
- src/main/java/com/devcourse/checkmoi/global/security/config/SecurityConfig.java
- src/test/java/com/devcourse/checkmoi/domain/book/stub/BookStub.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyMemberStub.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
- src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
- src/test/java/com/devcourse/checkmoi/domain/user/stub/UserStub.java
- src/test/java/com/devcourse/checkmoi/template/RepositoryTest.java
- 특정 책 ID를 받으면 해당 아이디에 대한 스터디 목록을 조회하는 기능 추가
- 현재 모집중인 스터디만 나오도록 구현
- 로그인을 하지 않아도 목록을 볼 수 있도록 시큐리티 체인에서 예외 설정 추가
- 스터디 목록에 대해서 커스텀 페이지네이션 처리
- API 문서화와 테스트 코드 작성 추가
- 페이지 처리를 포함하는 queryDSL 작성
- 현재 카운트 쿼리를 집계하는 필드를 Study 엔티티에 추가했으나 쿼리는 실행되나 값이 불러와지지 않는 이상현상이 발생한 상태입니다.
일단 해당 부분은 이슈로 남겨두고 나머지 부분 먼저 올리겠습니다.
- resolves #43
> ✨ feat : 특정 책에 대한 스터디 목록 조회 

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/exception/DuplicateStudyJoinRequestException.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/StudyMemberRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/DuplicateException.java
- src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyMemberStub.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
- 사용자가 스터디 참가 신청을 할 수 있는 기능을 구현
- 스터디 참가 신청을 이전에 하지 않았다면 해당 칼럼을 생성 아니라면 상태 확인후 DENIED인 경우에만 PENDING으로 변경
- 상태가 DENIED가 아니면 Duplicate Exception을 발생 시킴
- 스터디 참가 신청에 대한 테스트 코드 작성 및 API 문서화 완료
- resolves #52
> ✨  feat : 스터디 참가 신청 기능 구현

- src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/converter/StudyConverterTest.java
- 스터디 시작 날짜, 종료 날짜를 받도록 수정
- 스터디 상태를 RECRUTING으로 초기화
- 이에 맞게 API 문서 및 테스트코드 수정
- resolves #28
> ♻️ refactor : 스터디 등록 DTO 필드 추가

- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
allowedMethods "GET,POST,PUT,DELETE,HEAD";
allowedMethods "GET,POST,PUT,DELETE,HEAD,OPTIONS"
> POST 요청으로 보내더라도 OPTIONS 요청으로 갔으며 preflight 요청이 통과되지 않았다는 메시지가 있는 것을 알 수 있다. 
CORS로 요청을 할 때 보통 사전에 preflight 요청을 통해 서버 측에서 응답 헤더에 CORS와 관련에 헤더를 담아서 보내줘야 한다.
[참고자료](https://sun-22.tistory.com/60)
- resolves #68
> 🐛 fix : OAuth2 cors 허용 메서드 확대

- src/main/java/com/devcourse/checkmoi/domain/user/api/UserApi.java
- src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
- src/test/java/com/devcourse/checkmoi/domain/user/api/UserIntegrationTest.java
`/api/users/{userId}` → `/api/me` 로 변경
- resolves #76
> ♻️ refactor : 회원 정보 조회 API 변경

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMember.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyQueryServiceImpl.java
- src/main/resources/application-security.yml
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
스터디 정보를 조회하면, 책 정보와 스터디에 가입된 멤버 정보를 가지고 오는 API를 제작하였습니다.
```
{
"data": {
"study": {
"id": 1,
"name": "스터디 이름",
"thumbnailUrl": "스터디 썸네일 URL",
"description": "스터디 설명",
"currentParticipant": 2,
"maxParticipant": 5,
"gatherStartDate": "2022-08-02",
"gatherEndDate": "2022-08-02",
"studyStartDate": "2022-08-02",
"studyEndDate": "2022-08-02",
"book": {
"bookId": 1,
"title": "책 제목",
"author": "책 저자",
"publisher": "출판사",
"thumbnail": "책 썸네일"
}
},
"members": [
{
"id": 1,
"name": "fa4-4dee-9060-a8bdebe2ba8b",
"email": "asdf@asdf.com",
"profileImageUrl": "url"
},
{
"id": 2,
"name": "b7f-477a-b92c-31f5d1c637da",
"email": "asdf@asdf.com",
"profileImageUrl": "url"
}
]
}
}
```
- 현재 Repository 테스트시에 Stub에 id값이 존재해서 테스트가 깨지는 현상이 발생했습니다.
그래서 id 값이 없이 생성만을 도와주는 Util 클래스를 제작하였습니다.
- StudyMember의 BaseEntity …
> ✨ feat : 스터디 상세 조회

- src/main/java/com/devcourse/checkmoi/domain/study/converter/StudyConverter.java
- src/main/java/com/devcourse/checkmoi/domain/study/exception/NotAllowedStudyStatusException.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/study/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
- src/main/java/com/devcourse/checkmoi/global/exception/GlobalExceptionHandler.java
- src/test/java/com/devcourse/checkmoi/domain/study/converter/StudyConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/model/StudyStatusTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/model/StudyTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/study/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/study/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/stub/StudyStub.java
- src/test/java/com/devcourse/checkmoi/util/EntityGeneratorUtil.java
스터디 상태를 모집중 -> 진행중으로 변경시, 아직 PENDING 중이던 스터디 신청목록을 일괄 DENIED 로 변경합니다
스터디 상태가 진행완료 -> 진행중으로 다시 변경하는 것은 막습니다
상태 변경에 대한 정책을 적용하기 위해 
StudyStatus 에 NestStudyStatus 를 추가 정의 사용하여, 현재 상태에서 변경될 수 있는 , 허용하는 다음 스터디 상태를 정의해 두는 방식을 통해 서비스 레이어에서 변화가 많이 일어나지 않도록 하였습니다. 
하지만, 모집중->진행중 으로 변경 하는 경우에 한해서는 이 경우인지를 확인하여, PENDING 상태인 신청을 모두 거절해주어야 해서 이부분은 서비스 계층에 로직을 추가했습니다. 
- resolves #96
> ✨ feat : 스터디 상태를 진행중으로 상태변경시 스터디신청목록 처리

- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
스터디 내부에서 유저 DTO를 사용하는 부분을 제거하고, 스터디 내부 DTO로 변경하였습니다.
- resolves #60
> ♻️ refactor : 스터디 내부에서 쓰이는 유저 도메인 종속 제거

- src/main/java/com/devcourse/checkmoi/domain/token/service/TokenService.java
- src/main/java/com/devcourse/checkmoi/global/security/handler/OAuthAuthenticationSuccessHandler.java
- src/test/java/com/devcourse/checkmoi/domain/token/service/TokenServiceTest.java
refresh 토큰 삭제시 해당하는 유저가 refresh 토큰 레포에 없어도 로그아웃은 정삭작동한다
- resolves #124
> 🐛 fix : 토큰 삭제 로직 수정

- src/main/java/com/devcourse/checkmoi/domain/comment/api/CommentApi.java
- src/main/java/com/devcourse/checkmoi/domain/comment/converter/CommentConverter.java
- src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentRequest.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/api/PostApi.java
- src/main/java/com/devcourse/checkmoi/domain/post/converter/PostConverter.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostResponse.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepository.java
- src/main/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/api/PostApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/converter/PostConverterTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/repository/CustomPostRepositoryImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostQueryServiceImplTest.java
- 반환값에 작성자 이름과 프로필 이미지 댓글 수 추가
- requestBody로 검색하던 부분 queryPrameter 형식으로 변경
- convertTime 메서드 제거
GET `/api/posts` 
body { Id = 1 }
GET `/api/posts?studyId=1`
- resolves #131
> ♻️ refactor : 게시글 DTO 리팩토링

- src/main/java/com/devcourse/checkmoi/domain/book/api/BookApi.java
- src/main/java/com/devcourse/checkmoi/domain/post/exception/NotAllowedWriterException.java
- src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
- src/main/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/StudyMemberRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/ErrorMessage.java
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
- 스터디 장이 아닌 스터디원이 공지를 작성하려 할 경우 아래와 같은 에러를 발생시킵니다 
- 책 등록 api 가 POST 로 변경됨에 따라 Location header 를 포함한 응답을 보내는 부분을 추가하였습니다 
- StudyMemberRepository 에 대해 기존의 findByUser 를 findByUserId 로 변경하였습니다. 저는 쿼리메소드로 작성했는데 QueryDsl 로 작성하는게 좋을까요?
- @kimziou77 님 //TODO  validation 이건 어떤 검증로직을 TODO 로 등록하신 걸까요?? 주석이 많이 있는데 각각의 의미가 어떤 것들인지 잘 모르겠어 일단 남겨두었습니다
- resolves #134
> ✨  feat : 게시글 작성 서비스로직 권한검증 기능 추가 (#134)

- build.gradle
- src/main/java/com/devcourse/checkmoi/global/config/SecurityConfig.java
- src/main/java/com/devcourse/checkmoi/global/config/WebConfig.java
- src/main/java/com/devcourse/checkmoi/global/config/properties/AwsConfigProperties.java
- src/main/java/com/devcourse/checkmoi/global/config/properties/CorsConfigProperties.java
- src/main/java/com/devcourse/checkmoi/global/config/properties/SecurityConfigProperties.java
- src/main/resources/application-security.yml
- src/main/resources/application-test.yml
기존에 코드를 수정해야 변경할 수 있었던 시큐리티 자원 설정 부분을 yml 변경만을 통해 변경할 수 있도록 수정했습니다.
- **허용하는 origin은 cors.allowed.origin에 작성합니다**
---
- **필터를 무시하는 리소스는 `security.patterns.ignoring` 에 작성합니다**
- **로그인이 필요없는 요청은 `security.patterns.permit-all` 에 작성합니다**
스웨거 토큰 입력시 정상 작동합니다
- resolves #142
> 🔧 chore : yml을 통해 시큐리티 설정 정보 관리

- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
스터디 검색시 데이터가 중복으로 조회되는 문제를 해결
현재 group by studyId를 통해서 해결하였습니다. 다른 방안이 있을까요? 🤔 
- resolves #163
> 🐛 fix : 데이터 중복 조회 제거

- src/main/java/com/devcourse/checkmoi/domain/study/model/Study.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
- src/test/java/com/devcourse/checkmoi/domain/study/model/StudyStatusTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/model/StudyTest.java
- 스터디 상태에 "모집완료" 가 추가됨에 따라, 상태 변경에 대한 제약 로직을 수정하고 이를 테스트 하였습니다
이에 대한 거의 대부분의 경우의 수에 대한 시나리오 테스트를 StudyStatus 에 대한 유닛테스트로 추가했습니다
- 기존 Study 에 대한 edit 요청 로직에서 Study 내부의 changeStatus 를 사용하도록 하였었습니다. 해당 메소드 내부에서 스터디 상태 변경에 대한 제약을 검증하는 메소드를 요청합니다. 따라서 만약 기존의 Study 수정 api 를 통해 스터디 상태 변경 요청을 받는다면, 자동으로 스터디 상태 변경에 대한 제약을 검증하고 , 허용되지 않는 변경에 대해서 예외를 던집니다 
- resolves #168
> ✨ feat : 스터디에 모집완료 상태 추가 에 따른 상태 변경 제약 로직 수정 및 테스트 (#168)

- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- 스터디 신청 목록에 OAuth Token을 받는다고 명시하도록 스웨거 문서 수정
- 스터디 신청 승락 및 거절 시 status 값으로 받는 값을 대소문자 구분하지 않고 처리하도록 구현(ACCEPTED, DENIED)
- resolves #189
> ♻️ refactor : API 문서화 및 enum 소문자로 받도록 구현

- src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacade.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandService.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidator.java
- src/main/java/com/devcourse/checkmoi/domain/comment/service/validator/CommentValidatorImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
- src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacadeTest.java
- src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
- 댓글 존재 여부 확인 기능 추가
- 댓글 삭제시 현재 댓글 작성자 또는 스터디장인지 확인하고 아니라면 예외발생하는 기능 추가
- 이미 끝난 스터디에서는 댓글을 삭제하지 못하도록 하는 기능 추가
- 이에따른 테스트 코드 추가
- 현재 스터디장인지 확인해야 하는 부분에 대해서 좋은 방법이 떠오르지 않습니다. 지금 studyRepository를 이용해서 이를 해결했는데 스터디에서 다른 레포지터리를 가져와서 사용하는 것을 최대한 피하고 싶은데 좋은 방법이 떠오르지 않습니다. 🤔 
- resolves #136
> ♻️ refactor : 댓글 삭제 기능에 대한 validation 추가

- src/main/java/com/devcourse/checkmoi/domain/comment/facade/CommentFacade.java
- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyResponse.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomRepositoryUtil.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/StudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidator.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidatorImpl.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyServiceValidatorImplTest.java
- Study 쪽 QueryDsl 관련 공통 부분 메서드를 CustomRepositoryUtil로 묶었습니다
분리를 함에따라 CustomStudyRepository 355 line -> 232 line 으로 줄어들었습니다
- Study와 StudyMember 부분을 좀 더 명확히 구분하였습니다
- validation 하는 메서드의 이름을 check, validate 의 접두사로 통일하였습니다
- 유저 정보만을 반환하던 StudyAppliers에서 멤버 정보를 반환하는 StudyMemberInfo로 변경하였습니다
추가적으로 기존에 반환하던 값을 user로 묶고 member에 포함되어있는 id값을 추가하였습니다.
- CustomRepository가 거대해지고 있다고 느껴져 findStudyOwner와 같은 간단한 쿼리를 JPQL로 변경하였습니다
- resolves #193
> ♻️ refactor : 스터디신청승인

- src/main/java/com/devcourse/checkmoi/domain/comment/dto/CommentResponse.java
- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomCommentRepositoryImpl.java
- src/test/java/com/devcourse/checkmoi/domain/comment/api/CommentApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/comment/service/CommentQueryServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/util/DTOGeneratorUtil.java
- 댓글 목록 조회시 작성자 이름과 프로필 이미지를 포함해서 보내도록 변경
- userName과 userImage를 보내도록 변경했습니다.
- resolves #130
> ♻️ refactor : 댓글 목록 조회시 작성자 이름과 프로필 이미지를 포함해서 보내도록 변경

- src/main/java/com/devcourse/checkmoi/domain/book/dto/BookRequest.java
- src/main/java/com/devcourse/checkmoi/domain/post/dto/PostRequest.java
- src/main/java/com/devcourse/checkmoi/domain/post/model/PostCategory.java
- src/main/java/com/devcourse/checkmoi/domain/study/dto/StudyRequest.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyMemberStatus.java
- src/main/java/com/devcourse/checkmoi/domain/study/model/StudyStatus.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/global/annotation/CodeMappable.java
- src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnum.java
- src/main/java/com/devcourse/checkmoi/global/annotation/ValueOfEnumValidator.java
- src/test/java/com/devcourse/checkmoi/domain/book/api/BookApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/book/repository/BookRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/post/service/PostCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/repository/StudyRepositoryTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
sequencegenerator 
> 💥 현재상황은 열거타입 마다 프론트와 조율한 문자열의 형태가 다른 상황
아래 문자열로 "서버에 들어오고", "서버에서 보내줘야" 하는 상황
```java
@@@@@게시글 카테고리@@@@@
NOTICE
GENERAL
```
```java
@@@@@스터디 상태@@@@@
recruiting
recruitingFinished
inProgress
finished
```
```java
@@@@@스터디멤버 상태 @@@@@
ACCEPTED
DENIED
OWNED
```
---------------------
- 공통적인 처리를 하려면 공통 타입으로 처리할 수 있도록 하는게 좋을 거라 생각했습니다
- 기존의 Enum 타입으로 변환할 문자열들에 대한 검증을 수행하는 검증기도 변경함 ( CodeMappable 인터페이스의 메소드를 사용하여 검증함)
- StudyStatus 의 정적 팩토리 로직을 수정했습니다 ( nameOf 정적 팩토리 메소드가 사실상 CustomRepositoryImpl 에서만 사용되기는 하지만, 현재 얘가 null 을 반환하는 게 쪼끔 찝찝 하네요 ) 
- @JsonValue -> 직렬화시에 사용할 메소드를 지정합니다. ( StudyStatus 처럼 카멜케이스로 반환 요청 받은 애들은 , getMappingCode() 를 @JsonValue 로 설정해줘야 합니다 ) 
- ValueOfEnumValidator 로직을 변경하였습니다 -> CodeMappable 인터페이스 명세에 있는 메소드를 사용하도록
- 제가 생각하면서 변경을 한 부분들은 
-   비교 할 때는 모두 …
> ✨ feat : 특정한 문자열을 입출력하는 열거타입 정의 (#202)

- src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
- src/main/java/com/devcourse/checkmoi/global/exception/handler/GlobalExceptionHandler.java
용량 초과의 이미지 업로드 시 기존의 모습은 아래와 같았습니다
예외메시지를 출력하는 것으로 처리하였습니다
이력서 쓸 때 크기가 큰 이미지 첨부시 용량 초과 에러메시지 뜨는 것 처럼 생각하면 좋을듯 합니당
예외메시지를 추가하고 GlobalExceptionHandler 에서 해당 예외를 처리하도록 추가하였습니다
비동기로 변경하는 PR 과 분리하여 올립니다!
- resolves #173
> ✨ feat :  이미지 용량 초과 예외메시지 추가 (#173)

- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepository.java
- src/main/java/com/devcourse/checkmoi/domain/study/repository/CustomStudyRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleService.java
- src/main/java/com/devcourse/checkmoi/global/scheduler/ScheduleManager.java
- src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/schedule/StudyScheduleServiceTest.java
스터디 진행 종료 날짜가 지난 스터디들을 진행완료 상태로 변경합니다.
각 상태변경은 각각의 트랜잭션에서 이루어집니다.
기존 스케줄러 태스크와 비동기적으로 동작합니다 
추가적인 로직에 대한 테스트 추가
커밋메시지에 이슈번호를 잘못 적었습니다
- resolves #224
> ✨ feat :  진행기간이 지난 스터디들을 진행완료상태로 변경하는 기능 추가 (#173)

- src/main/java/com/devcourse/checkmoi/domain/study/api/StudyApi.java
- src/main/java/com/devcourse/checkmoi/domain/study/exception/StudyJoinMaximumReachedException.java
- src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyFacade.java
- src/main/java/com/devcourse/checkmoi/domain/study/facade/StudyFacadeImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImpl.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidator.java
- src/main/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImpl.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepository.java
- src/main/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImpl.java
- src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryService.java
- src/main/java/com/devcourse/checkmoi/domain/user/service/UserQueryServiceImpl.java
- src/main/java/com/devcourse/checkmoi/global/exception/error/ErrorMessage.java
- src/test/java/com/devcourse/checkmoi/domain/study/api/StudyApiTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/facade/StudyFacadeImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/StudyCommandServiceImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/study/service/validator/StudyValidatorImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/user/repository/CustomUserRepositoryImplTest.java
- src/test/java/com/devcourse/checkmoi/domain/user/service/UserQueryServiceImplTest.java
- facade 패턴을 적용하여 유저의 스터디 수를 유저 서비스에게 가져오도록 수정
- 최대 스터디수 (10명) 만큼 가입했을 경우 예외 발생
- 신청 후 사용자가 스터디가 10개 넘었을 때 승인시 예외 발생하도록 변경
- 해당 예외시 발생하는 exception class 추가
- 이에 따른 테스트 코드 수정
- resolves #223
> ♻️ refactor : 현재 유저가 스터디에 최대 스터디수 만큼 가입했을 경우 예외 처리

- src/main/java/com/devcourse/checkmoi/domain/comment/repository/CustomCommentRepositoryImpl.java
- 여러명의 유저가 댓글을 작성시 일정 개수가 넘어져서 결과가 댓글 작성순이 아닌 뒤죽박죽 섞여서 나오는 현상이 발생
- 값을 DB에 조회할때 orderby를 통해 댓글 최신 작성순으로 정렬하도록 로직 추가
- resolves #244
> 🐛 fix : 댓글 조회시 순서가 뒤죽박죽으로 조회되는 현상 해결

- build.gradle
- src/main/java/com/devcourse/checkmoi/domain/study/api/ScheduleApi.java
- src/main/java/com/devcourse/checkmoi/global/scheduler/Scheduler.java
- src/test/java/com/devcourse/checkmoi/global/scheduler/SchedulerTest.java
- 스케줄러의 동작을 api 를 통해 호출할 수 있도록 추가
- 3.1.0 으로 버전 업그레이드
- 스케줄러의 메소드들은 private-package 로 유지하고 , 일시적으로 허용해 놓는 스케줄러 동작을 시연하는 api 이므로 scheduler 와 동일한 로직이지만 따로 작성하였습니다. 
- resolves #252
> ✨ feat : 스케줄러 동작 api 추가 (#252)
